name: Docs2Synth
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pytorch
  - pytest
  - python=3.10
  - black
  - isort
  - flake8
  - yaml
  - conda=25.9.0
  - pyyaml
  - pandas
  - pillow
  - pip:
      - paddlepaddle==3.2.0
      - shapely>=1.8
      - scikit-image>=0.21
